sudo: required
dist: trusty

branches:
  except:
    - documentation
    
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:beineri/opt-qt57-trusty -y
  - sudo apt-get update -qq
  
install:
  - sudo apt-get install g++-4.9 -y
  - export CXX="g++-4.9"
  - sudo apt-get install qt57base -y
  - sudo apt-get install qt57xmlpatterns -y
  - cmake --version
  
script:
  - source /opt/qt57/bin/qt57-env.sh
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make package
