sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:beineri/opt-qt56-trusty -y
  - sudo apt-get update -qq
  
install:
  - sudo apt-get install g++-4.9 -y
  - export CXX="g++-4.9"
  - sudo apt-get install qt56base -y
  - sudo apt-get install qt56xmlpatterns -y
  
script:
  - source /opt/qt56/bin/qt56-env.sh
  - mkdir build
  - cd build
  - cmake ..
  - make
