install:
  - set QTDIR=C:\Qt\5.5\msvc2013_64
  - set PATH=%PATH%;%QTDIR%\bin;
  
before_build:
  - mkdir build
  - cd build
  - cmake ..
  - dir
  
#platform:
#  - x86
#  - Any CPU

#configuration:
#  - Debug
#  - Release

matrix:
  fast_finish: true
 
build:
  parallel: true
  project: "build\ALL_BUILD.vcxproj"
