install:
  - set QTDIR=C:\Qt\5.5\msvc2013_64
  - set PATH=%PATH%;%QTDIR%\bin;
  
before_build:
  - mkdir build
  - cd build
  - cmake ..
beuild:
  - msbuild "build\ALL_BUILD.vcxproj" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
 
