os: Visual Studio 2013
version: 1.0.0.{build}

install:
  - set QTDIR=C:\Qt\5.5\msvc2013
  - set PATH=%PATH%;%QTDIR%\bin;
  
before_build:
  - md build
  - cd build
  - cmake ..
  - cd ..
  - dir
  
configuration:
  - Debug
  - Release
 
build:
  project: build/gtest-runner-HEAD.sln

deploy:
  release: Windows Installer - v$(appveyor_repo_tag_name)
  description: gtest-runner automated binary installer for windows
  provider: GitHub
  auth_token:
    secure: FtWS/a/Vb7xeJrcZYs+9AtDnQ3aNqfL56NnjMYFvwokdPUP4qo4BImfPFr4H67A6
  artifact: Release/gtest-runner-$(appveyor_repo_tag_name)-win64.exe
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
	configuration: Release 
    appveyor_repo_tag: true        # deploy on tag push only