install:
  - set QTDIR=C:\Qt\5.5\msvc2013_64
  - set PATH=%PATH%;%QTDIR%\bin;
  
before_build:
  - md build
  - cd build
  - cmake ..
  - cd ..
  - dir

platform:
  - x64
  
#configuration:
#  - Debug
#  - Release
 
build:
  Project: build/gtest-gui-HEAD.sln
